import React, { useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { Activity, Bell, CalendarDays, CreditCard, FileText, LayoutDashboard, Menu, Pill, Search, Settings, Users, X, Plus, Phone, Mail, UserRound } from 'lucide-react';
import Visits from './Visits';
import './styles.css';

type Status = 'Pending' | 'Approved' | 'Rejected' | 'Under review';
type Patient = { id:string; name:string; dob:string; phone:string; email:string; status:'Active'|'Inactive'; lastVisit:string };
type Case = { id:string; patientId:string; patientName:string; type:string; created:string; amount:number; status:Status; notes:string };
const modules=[['Dashboard',<LayoutDashboard size={18}/>],['Patients',<Users size={18}/>],['Cases',<FileText size={18}/>],['Visits',<CalendarDays size={18}/>],['Invoices',<CreditCard size={18}/>],['Payments',<Activity size={18}/>],['Medicines',<Pill size={18}/>]];
const patients0:Patient[]=[
{id:'RSQ-P-000248',name:'Maria Georgiou',dob:'1988-04-12',phone:'+357 99 123456',email:'maria.georgiou@example.com',status:'Active',lastVisit:'14 Aug 2026'},
{id:'RSQ-P-000247',name:'Andreas Nicolaou',dob:'1975-09-21',phone:'+357 96 234567',email:'andreas.nicolaou@example.com',status:'Active',lastVisit:'13 Aug 2026'},
{id:'RSQ-P-000246',name:'Eleni Christou',dob:'1992-02-03',phone:'+357 97 345678',email:'eleni.christou@example.com',status:'Active',lastVisit:'12 Aug 2026'},
{id:'RSQ-P-000245',name:'Petros Ioannou',dob:'1969-11-18',phone:'+357 99 456789',email:'petros.ioannou@example.com',status:'Inactive',lastVisit:'28 Jul 2026'}];
const cases0:Case[]=[
{id:'#RSQ-1048',patientId:'RSQ-P-000248',patientName:'Maria Georgiou',type:'Consultation',created:'14 Aug 2026',amount:180,status:'Pending',notes:'Awaiting supporting documents.'},
{id:'#RSQ-1047',patientId:'RSQ-P-000247',patientName:'Andreas Nicolaou',type:'Follow-up',created:'13 Aug 2026',amount:95,status:'Approved',notes:'Coverage confirmed.'},
{id:'#RSQ-1046',patientId:'RSQ-P-000246',patientName:'Eleni Christou',type:'Laboratory',created:'12 Aug 2026',amount:420,status:'Under review',notes:'Medical report requested.'},
{id:'#RSQ-1045',patientId:'RSQ-P-000245',patientName:'Petros Ioannou',type:'Medication',created:'10 Aug 2026',amount:75,status:'Approved',notes:'Eligible under policy.'}];
const badge=(s:Status|string)=>s==='Approved'||s==='Active'||s==='Completed'?'approved':s==='Rejected'||s==='Cancelled'?'rejected':s==='Pending'?'pending':'review';

function App(){
 const [active,setActive]=useState('Dashboard'),[sidebarOpen,setSidebarOpen]=useState(false); const [patients,setPatients]=useState(patients0); const [cases,setCases]=useState(cases0);
 const [pSearch,setPSearch]=useState(''),[cSearch,setCSearch]=useState(''),[cFilter,setCFilter]=useState('All'); const [patientForm,setPatientForm]=useState(false),[caseForm,setCaseForm]=useState(false),[selected,setSelected]=useState<Patient|null>(null);
 const [pf,setPf]=useState({name:'',dob:'',phone:'',email:''}); const [cf,setCf]=useState({patientId:'',type:'Consultation',amount:'',notes:''});
 const fp=useMemo(()=>{const q=pSearch.toLowerCase();return patients.filter(p=>!q||`${p.id} ${p.name} ${p.phone} ${p.email}`.toLowerCase().includes(q))},[pSearch,patients]);
 const fc=useMemo(()=>{const q=cSearch.toLowerCase();return cases.filter(c=>(cFilter==='All'||c.status===cFilter)&&(!q||`${c.id} ${c.patientId} ${c.patientName} ${c.type}`.toLowerCase().includes(q)))},[cSearch,cFilter,cases]);
 const createPatient=(e:React.FormEvent)=>{e.preventDefault();if(!pf.name.trim())return;const id=`RSQ-P-${String(249+patients.length-4).padStart(6,'0')}`;setPatients([{...pf,id,status:'Active',lastVisit:'—'},...patients]);setPf({name:'',dob:'',phone:'',email:''});setPatientForm(false)};
 const createCase=(e:React.FormEvent)=>{e.preventDefault();const p=patients.find(x=>x.id===cf.patientId);if(!p||!cf.amount)return;const id=`#RSQ-${1049+cases.length-4}`;setCases([{id,patientId:p.id,patientName:p.name,type:cf.type,created:'14 Aug 2026',amount:Number(cf.amount),status:'Pending',notes:cf.notes||'No notes added.'},...cases]);setCf({patientId:'',type:'Consultation',amount:'',notes:''});setCaseForm(false)};
 const go=(m:string)=>{setActive(m);setSidebarOpen(false)};
 return <div className="shell">
  <aside className={`sidebar ${sidebarOpen?'open':''}`}><div className="brand"><div className="brand-mark">R</div><div><strong>RESQ</strong><span>ERP</span></div><button className="close-mobile" onClick={()=>setSidebarOpen(false)}><X size={20}/></button></div><div className="nav-label">WORKSPACE</div><nav>{modules.map(([n,i])=><button key={n} className={active===n?'nav-item active':'nav-item'} onClick={()=>go(n as string)}>{i}<span>{n}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={18}/><span>Settings</span></button><div className="user-card"><div className="avatar">VS</div><div><strong>RESQ Admin</strong><small>Administrator</small></div></div></div></aside>
  {sidebarOpen&&<button className="overlay" onClick={()=>setSidebarOpen(false)}/>}<section className="main-area"><header className="topbar"><button className="mobile-menu" onClick={()=>setSidebarOpen(true)}><Menu size={22}/></button><div className="search"><Search size={18}/><input placeholder="Search patients, cases, invoices..."/></div><button className="icon-button"><Bell size={19}/><i/></button><div className="top-avatar">VS</div></header><main className="content">
  {active==='Dashboard'&&<><div className="page-heading"><div><p className="eyebrow">RESQ MANAGEMENT SYSTEM</p><h1>Dashboard</h1><p className="muted">Overview of your operations and activity.</p></div><button className="primary" onClick={()=>{setActive('Cases');setCaseForm(true)}}>+ New case</button></div><div className="stats-grid">{[['Active patients',patients.length,'+12 this month'],['Open cases',cases.filter(c=>c.status==='Pending'||c.status==='Under review').length,'Pending review'],['Visits today','24','6 remaining'],['Outstanding','€8,420','14 invoices']].map(([a,b,c])=><div className="stat-card" key={a as string}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-header"><div><h2>Recent cases</h2><p>Latest patient activity</p></div><button className="link-button" onClick={()=>go('Cases')}>View all</button></div><div className="table-wrap"><table><thead><tr><th>Case</th><th>Patient</th><th>Type</th><th>Status</th></tr></thead><tbody>{cases.slice(0,4).map(c=><tr key={c.id}><td>{c.id}</td><td>{c.patientName}</td><td>{c.type}</td><td><b className={`badge ${badge(c.status)}`}>{c.status}</b></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-header"><div><h2>Quick actions</h2><p>Common operations</p></div></div><div className="quick-grid"><button onClick={()=>{go('Patients');setPatientForm(true)}}><Users size={20}/><span>New patient</span></button><button onClick={()=>{go('Cases');setCaseForm(true)}}><FileText size={20}/><span>New case</span></button><button onClick={()=>go('Visits')}><CalendarDays size={20}/><span>Record visit</span></button><button onClick={()=>go('Invoices')}><CreditCard size={20}/><span>Create invoice</span></button></div></section></div></>}
  {active==='Patients'&&<><div className="page-heading"><div><p className="eyebrow">PATIENT MANAGEMENT</p><h1>Patients</h1><p className="muted">Search, register and manage patient records.</p></div><button className="primary" onClick={()=>setPatientForm(true)}><Plus size={17}/> New patient</button></div><div className="patient-toolbar"><div className="patient-search"><Search size={18}/><input value={pSearch} onChange={e=>setPSearch(e.target.value)} placeholder="Search by patient ID, name, phone or email..."/></div><span className="result-count">{fp.length} patients</span></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Patient ID</th><th>Patient</th><th>Date of birth</th><th>Contact</th><th>Status</th><th>Last visit</th></tr></thead><tbody>{fp.map(p=><tr key={p.id} className="clickable-row" onClick={()=>setSelected(p)}><td><strong>{p.id}</strong></td><td><div className="patient-name"><span className="mini-avatar"><UserRound size={16}/></span>{p.name}</div></td><td>{p.dob}</td><td><div className="contact-cell"><span><Phone size={13}/>{p.phone}</span><span><Mail size={13}/>{p.email}</span></div></td><td><b className={`badge ${badge(p.status)}`}>{p.status}</b></td><td>{p.lastVisit}</td></tr>)}</tbody></table></div></section></>}
  {active==='Cases'&&<><div className="page-heading"><div><p className="eyebrow">CASE MANAGEMENT</p><h1>Cases</h1><p className="muted">Track cases, decisions, amounts and supporting documentation.</p></div><button className="primary" onClick={()=>setCaseForm(true)}><Plus size={17}/> New case</button></div><div className="case-summary"><div><span>Total</span><strong>{cases.length}</strong></div><div><span>Pending</span><strong>{cases.filter(c=>c.status==='Pending').length}</strong></div><div><span>Under review</span><strong>{cases.filter(c=>c.status==='Under review').length}</strong></div><div><span>Approved amount</span><strong>€{cases.filter(c=>c.status==='Approved').reduce((s,c)=>s+c.amount,0).toLocaleString()}</strong></div></div><div className="patient-toolbar"><div className="patient-search"><Search size={18}/><input value={cSearch} onChange={e=>setCSearch(e.target.value)} placeholder="Search case ID, patient, type..."/></div><select className="filter-select" value={cFilter} onChange={e=>setCFilter(e.target.value)}><option>All</option><option>Pending</option><option>Under review</option><option>Approved</option><option>Rejected</option></select></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Case</th><th>Patient</th><th>Type</th><th>Created</th><th>Amount</th><th>Decision</th><th>Actions</th></tr></thead><tbody>{fc.map(c=><tr key={c.id}><td><strong>{c.id}</strong><small className="cell-sub">{c.notes}</small></td><td><strong>{c.patientName}</strong><small className="cell-sub">{c.patientId}</small></td><td>{c.type}</td><td>{c.created}</td><td>€{c.amount.toLocaleString()}</td><td><b className={`badge ${badge(c.status)}`}>{c.status}</b></td><td><div className="decision-actions">{c.status!=='Approved'&&<button onClick={()=>setCases(cases.map(x=>x.id===c.id?{...x,status:'Approved'}:x))}>Approve</button>}{c.status!=='Rejected'&&<button onClick={()=>setCases(cases.map(x=>x.id===c.id?{...x,status:'Rejected'}:x))}>Reject</button>}{c.status==='Pending'&&<button onClick={()=>setCases(cases.map(x=>x.id===c.id?{...x,status:'Under review'}:x))}>Review</button>}</div></td></tr>)}</tbody></table></div></section></>}
  {active==='Visits'&&<Visits/>}
  {!['Dashboard','Patients','Cases','Visits'].includes(active)&&<section className="empty-module"><div className="empty-icon">{modules.find(x=>x[0]===active)?.[1]}</div><h2>{active} module</h2><p>The module structure is ready. We will implement its database, forms, search, filters and workflows next.</p><button className="primary">Configure {active}</button></section>}
 </main></section>
 {patientForm&&<div className="modal-backdrop" onMouseDown={()=>setPatientForm(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">PATIENT REGISTRATION</p><h2>New patient</h2></div><button className="modal-close" onClick={()=>setPatientForm(false)}><X size={20}/></button></div><form onSubmit={createPatient}><div className="form-grid"><label>Full name<input required value={pf.name} onChange={e=>setPf({...pf,name:e.target.value})}/></label><label>Date of birth<input type="date" value={pf.dob} onChange={e=>setPf({...pf,dob:e.target.value})}/></label><label>Phone<input value={pf.phone} onChange={e=>setPf({...pf,phone:e.target.value})}/></label><label>Email<input type="email" value={pf.email} onChange={e=>setPf({...pf,email:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setPatientForm(false)}>Cancel</button><button className="primary">Create patient</button></div></form></div></div>}
 {caseForm&&<div className="modal-backdrop" onMouseDown={()=>setCaseForm(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">CASE REGISTRATION</p><h2>New case</h2></div><button className="modal-close" onClick={()=>setCaseForm(false)}><X size={20}/></button></div><form onSubmit={createCase}><div className="form-grid"><label>Patient<select required value={cf.patientId} onChange={e=>setCf({...cf,patientId:e.target.value})}><option value="">Select patient...</option>{patients.map(p=><option key={p.id} value={p.id}>{p.id} — {p.name}</option>)}</select></label><label>Case type<select value={cf.type} onChange={e=>setCf({...cf,type:e.target.value})}><option>Consultation</option><option>Follow-up</option><option>Laboratory</option><option>Medication</option><option>Hospitalization</option><option>Other</option></select></label><label>Claim / case amount (€)<input required type="number" min="0" step="0.01" value={cf.amount} onChange={e=>setCf({...cf,amount:e.target.value})}/></label><label>Notes<textarea value={cf.notes} onChange={e=>setCf({...cf,notes:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setCaseForm(false)}>Cancel</button><button className="primary">Create case</button></div></form></div></div>}
 {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div className="profile-title"><div className="profile-avatar"><UserRound/></div><div><p className="eyebrow">PATIENT PROFILE</p><h2>{selected.name}</h2><span>{selected.id}</span></div></div><button className="modal-close" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="profile-grid"><div><small>Date of birth</small><strong>{selected.dob}</strong></div><div><small>Status</small><strong><b className={`badge ${badge(selected.status)}`}>{selected.status}</b></strong></div><div><small>Phone</small><strong>{selected.phone}</strong></div><div><small>Email</small><strong>{selected.email}</strong></div></div><div className="profile-section"><h3>Patient history</h3><p>Visits, cases, invoices and medicines will be linked here as the database layer is added.</p></div></div></div>}
 </div>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
