import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Mail,Phone,Plus,Search,UserRound,X,Upload,FileSpreadsheet,Edit3,Trash2,RotateCcw} from 'lucide-react';
import {Patient} from './types';import {badge} from './data';
type Props={patients:Patient[];onAdd:(p:Patient)=>void};
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parse=(line:string)=>{const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(cur.trim());cur='';}else cur+=c;}out.push(cur.trim());return out};const headers=parse(lines[0]);return lines.slice(1).map(line=>{const vals=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']))})}
export default function Patients({patients:initialPatients,onAdd}:Props){
 const[patients,setPatients]=useState<Patient[]>(initialPatients);const[search,setSearch]=useState('');const[statusFilter,setStatusFilter]=useState<'ACTIVE'|'INACTIVE'|'ALL'>('ACTIVE');const[show,setShow]=useState(false);const[showImport,setShowImport]=useState(false);const[selected,setSelected]=useState<Patient|null>(null);const[editing,setEditing]=useState(false);const[form,setForm]=useState({name:'',dob:'',phone:'',email:''});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[history,setHistory]=useState<any>(null);const[importRows,setImportRows]=useState<any[]>([]);const[importResult,setImportResult]=useState<any>(null);const[fileRef]=useState(()=>React.createRef<HTMLInputElement>());
 // The API is the source of truth. Do not overwrite current data with the parent's older snapshot.
 useEffect(()=>{let cancelled=false;const timer=window.setTimeout(async()=>{try{setLoading(true);setError('');const response=await fetch(`/api/patients?search=${encodeURIComponent(search.trim())}&status=${statusFilter}`,{cache:'no-store'});if(!response.ok)throw new Error('Unable to load patients');const data=await response.json();if(!cancelled)setPatients(Array.isArray(data)?data:[])}catch(err){if(!cancelled)setError(err instanceof Error?err.message:'Unable to load patients')}finally{if(!cancelled)setLoading(false)}},180);return()=>{cancelled=true;window.clearTimeout(timer)}},[search,statusFilter]);
 const filtered=useMemo(()=>patients,[patients]);
 const openProfile=async(p:Patient)=>{setSelected(p);setEditing(false);setHistory(null);setError('');try{const response=await fetch(`/api/patients?id=${encodeURIComponent(p.id)}`,{cache:'no-store'});if(response.ok){const data=await response.json();setSelected(data);setHistory(data.history)}}catch{}};
 const openEdit=(p:Patient)=>{setSelected(p);setEditing(true);setForm({name:p.name,dob:p.dob||'',phone:p.phone||'',email:p.email||''});setError('')};
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||saving)return;try{setSaving(true);setError('');const response=await fetch('/api/patients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to create patient');setPatients(current=>[data,...current.filter(p=>p.id!==data.id)]);onAdd(data);setForm({name:'',dob:'',phone:'',email:''});setShow(false)}catch(err){setError(err instanceof Error?err.message:'Unable to create patient')}finally{setSaving(false)}};
 const update=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!form.name.trim()||saving)return;try{setSaving(true);setError('');const response=await fetch(`/api/patients?id=${encodeURIComponent(selected.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to update patient');setPatients(current=>current.map(p=>p.id===data.id?data:p));setSelected(data);setEditing(false)}catch(err){setError(err instanceof Error?err.message:'Unable to update patient')}finally{setSaving(false)}};
 const changeStatus=async(p:Patient,status:'ACTIVE'|'INACTIVE')=>{const action=status==='INACTIVE'?'deactivate':'restore';if(status==='INACTIVE'&&!window.confirm(`Deactivate ${p.name}? The patient and all history will remain in the database.`))return;try{setError('');const response=await fetch(`/api/patients?id=${encodeURIComponent(p.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const data=await response.json();if(!response.ok)throw new Error(data.error||`Unable to ${action} patient`);setPatients(current=>current.filter(x=>x.id!==p.id));if(selected?.id===p.id)setSelected(data)}catch(err){setError(err instanceof Error?err.message:`Unable to ${action} patient`)}};
 const chooseFile=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const rows=parseCsv(String(reader.result||''));setImportRows(rows);setImportResult(null);setError(rows.length?'':'CSV contains no data rows')}catch{setError('Unable to read CSV')}};reader.readAsText(file)};
 const importPatients=async(preview:boolean)=>{const r=await fetch('/api/patients/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:importRows,preview})});const x=await r.json();if(!r.ok){setError(x.error||'Unable to import patients');return}setImportResult(x);if(!preview){setShowImport(false);setImportRows([]);setTimeout(()=>window.location.reload(),300)}};
 return <><div className="page-heading"><div><p className="eyebrow">PATIENT MANAGEMENT</p><h1>Patients</h1><p className="muted">Search, register and manage patient records.</p></div><div style={{display:'flex',gap:8}}><button className="secondary" onClick={()=>{setShowImport(true);setImportResult(null)}}><Upload size={16}/> Import CSV</button><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/> New patient</button></div></div>
 <div className="patient-toolbar"><div className="patient-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by patient ID, name, phone or email..."/></div><div style={{display:'flex',gap:6,alignItems:'center'}}><button className={statusFilter==='ACTIVE'?'primary':'secondary'} onClick={()=>setStatusFilter('ACTIVE')}>Active</button><button className={statusFilter==='INACTIVE'?'primary':'secondary'} onClick={()=>setStatusFilter('INACTIVE')}>Inactive</button><button className={statusFilter==='ALL'?'primary':'secondary'} onClick={()=>setStatusFilter('ALL')}>All</button><span className="result-count">{loading?'Loading…':`${filtered.length} patients`}</span></div></div>{error&&<div className="panel" style={{marginBottom:16,padding:14}}>{error}</div>}
 <section className="panel"><div className="table-wrap"><table><thead><tr><th>Patient ID</th><th>Patient</th><th>Date of birth</th><th>Contact</th><th>Status</th><th>Last visit</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="clickable-row" onClick={()=>openProfile(p)}><td><strong>{p.id}</strong></td><td><div className="patient-name"><span className="mini-avatar"><UserRound size={16}/></span>{p.name}</div></td><td>{p.dob||'—'}</td><td><div className="contact-cell"><span><Phone size={13}/>{p.phone||'—'}</span><span><Mail size={13}/>{p.email||'—'}</span></div></td><td><b className={`badge ${badge(p.status)}`}>{p.status}</b></td><td>{p.lastVisit}</td><td onClick={e=>e.stopPropagation()}><div style={{display:'flex',gap:4}}><button className="secondary" title="Edit patient" onClick={()=>openEdit(p)}><Edit3 size={15}/></button>{p.status==='Active'?<button className="secondary" title="Deactivate patient" onClick={()=>changeStatus(p,'INACTIVE')}><Trash2 size={15}/></button>:<button className="secondary" title="Restore patient" onClick={()=>changeStatus(p,'ACTIVE')}><RotateCcw size={15}/></button>}</div></td></tr>)}</tbody></table></div></section>
 {showImport&&<div className="modal-backdrop" onMouseDown={()=>setShowImport(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">DATA IMPORT</p><h2>Import patients from CSV</h2><p className="muted">Upload CSV, preview duplicates and then import.</p></div><button className="modal-close" onClick={()=>setShowImport(false)}><X size={20}/></button></div><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={chooseFile}/>{importRows.length>0&&<><div className="profile-section"><h3><FileSpreadsheet size={17}/> Preview</h3><p>{importRows.length} rows detected. The system checks Patient ID, email and phone for existing patients.</p><div className="table-wrap"><table><thead><tr>{Object.keys(importRows[0]).slice(0,5).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{importRows.slice(0,5).map((row,i)=><tr key={i}>{Object.keys(importRows[0]).slice(0,5).map(k=><td key={k}>{row[k]}</td>)}</tr>)}</tbody></table></div></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>importPatients(true)}>Validate / Preview</button><button type="button" className="primary" onClick={()=>importPatients(false)}>Import patients</button></div></>}{importResult&&<div className="profile-section"><h3>Import result</h3><p>{importResult.newPatients} new · {importResult.existing} already existing · {importResult.errors?.length||0} errors.</p></div>}</div></div>}
 {show&&<div className="modal-backdrop" onMouseDown={()=>!saving&&setShow(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">PATIENT REGISTRATION</p><h2>New patient</h2></div><button className="modal-close" onClick={()=>!saving&&setShow(false)}><X size={20}/></button></div><form onSubmit={create}><div className="form-grid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date of birth<input type="date" value={form.dob} onChange={e=>setForm({...form,dob:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>!saving&&setShow(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Create patient'}</button></div></form></div></div>}
 {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div className="profile-title"><div className="profile-avatar"><UserRound/></div><div><p className="eyebrow">PATIENT PROFILE</p><h2>{selected.name}</h2><span>{selected.id}</span></div></div><button className="modal-close" onClick={()=>setSelected(null)}><X size={20}/></button></div>{editing?<form onSubmit={update}><div className="form-grid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Date of birth<input type="date" value={form.dob} onChange={e=>setForm({...form,dob:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setEditing(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save changes'}</button></div></form>:<><div className="profile-grid"><div><small>Date of birth</small><strong>{selected.dob||'Not provided'}</strong></div><div><small>Status</small><strong><b className={`badge ${badge(selected.status)}`}>{selected.status}</b></strong></div><div><small>Phone</small><strong>{selected.phone||'Not provided'}</strong></div><div><small>Email</small><strong>{selected.email||'Not provided'}</strong></div></div><div className="form-actions"><button className="secondary" onClick={()=>openEdit(selected)}><Edit3 size={15}/> Edit</button>{selected.status==='Active'?<button className="secondary" onClick={()=>changeStatus(selected,'INACTIVE')}><Trash2 size={15}/> Deactivate</button>:<button className="secondary" onClick={()=>changeStatus(selected,'ACTIVE')}><RotateCcw size={15}/> Restore</button>}</div><div className="profile-section"><h3>Patient history</h3>{history?<p>{history.cases?.length||0} cases · {history.visits?.length||0} visits · {history.invoices?.length||0} invoices · {history.medications?.length||0} medicines</p>:<p>Loading patient history…</p>}</div></>}</div></div>}
 </>;
}
