import React, { useMemo, useState } from 'react';
import { CheckCircle2, CreditCard, Plus, Search, X } from 'lucide-react';

type Payment = { id:string; invoiceId:string; patient:string; date:string; amount:number; method:'Bank transfer'|'Card'|'Cash'; reference:string; status:'Completed'|'Pending' };
const initial:Payment[]=[
 {id:'PAY-00041',invoiceId:'INV-00124',patient:'Maria Georgiou',date:'14 Aug 2026',amount:180,method:'Bank transfer',reference:'TRX-88421',status:'Completed'},
 {id:'PAY-00040',invoiceId:'INV-00123',patient:'Andreas Nicolaou',date:'13 Aug 2026',amount:95,method:'Card',reference:'CARD-5521',status:'Completed'},
 {id:'PAY-00039',invoiceId:'INV-00122',patient:'Eleni Christou',date:'12 Aug 2026',amount:220,method:'Bank transfer',reference:'TRX-88402',status:'Pending'},
];
export default function Payments(){
 const [payments,setPayments]=useState(initial); const [search,setSearch]=useState(''); const [show,setShow]=useState(false);
 const [form,setForm]=useState({invoiceId:'',patient:'',amount:'',method:'Bank transfer',reference:''});
 const filtered=useMemo(()=>{const q=search.toLowerCase();return payments.filter(p=>!q||`${p.id} ${p.invoiceId} ${p.patient} ${p.reference}`.toLowerCase().includes(q))},[search,payments]);
 const create=(e:React.FormEvent)=>{e.preventDefault();if(!form.invoiceId||!form.patient||!form.amount)return;const id=`PAY-${String(42+payments.length-initial.length).padStart(5,'0')}`;setPayments([{id,invoiceId:form.invoiceId,patient:form.patient,date:'14 Aug 2026',amount:Number(form.amount),method:form.method as Payment['method'],reference:form.reference||'—',status:'Completed'},...payments]);setForm({invoiceId:'',patient:'',amount:'',method:'Bank transfer',reference:''});setShow(false)};
 return <><div className="page-heading"><div><p className="eyebrow">PAYMENT MANAGEMENT</p><h1>Payments</h1><p className="muted">Record, search and reconcile incoming payments.</p></div><button className="primary" onClick={()=>setShow(true)}><Plus size={17}/> New payment</button></div><div className="case-summary"><div><span>Total payments</span><strong>{payments.length}</strong></div><div><span>Completed</span><strong>{payments.filter(p=>p.status==='Completed').length}</strong></div><div><span>Pending</span><strong>{payments.filter(p=>p.status==='Pending').length}</strong></div><div><span>Collected</span><strong>€{payments.filter(p=>p.status==='Completed').reduce((s,p)=>s+p.amount,0).toLocaleString()}</strong></div></div><div className="patient-toolbar"><div className="patient-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search payment ID, invoice, patient or reference..."/></div><span className="result-count">{filtered.length} payments</span></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Payment</th><th>Invoice</th><th>Patient</th><th>Date</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.id}</strong><small className="cell-sub">{p.reference}</small></td><td>{p.invoiceId}</td><td>{p.patient}</td><td>{p.date}</td><td>€{p.amount.toLocaleString()}</td><td>{p.method}</td><td><b className={`badge ${p.status==='Completed'?'approved':'pending'}`}>{p.status}</b></td></tr>)}</tbody></table></div></section>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">PAYMENT REGISTRATION</p><h2>New payment</h2></div><button className="modal-close" onClick={()=>setShow(false)}><X size={20}/></button></div><form onSubmit={create}><div className="form-grid"><label>Invoice ID<input required value={form.invoiceId} onChange={e=>setForm({...form,invoiceId:e.target.value})} placeholder="INV-00125"/></label><label>Patient<input required value={form.patient} onChange={e=>setForm({...form,patient:e.target.value})}/></label><label>Amount (€)<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Payment method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>Bank transfer</option><option>Card</option><option>Cash</option></select></label><label>Reference<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setShow(false)}>Cancel</button><button className="primary"><CheckCircle2 size={16}/> Record payment</button></div></form></div></div>}</>;
}