import React,{useEffect,useState} from 'react';import {BarChart3,Boxes,FileText,Receipt,Users,Wallet,X} from 'lucide-react';
export default function Reports(){const[s,setS]=useState<any>(null);const[c,setC]=useState<any[]>([]);const[invoices,setInvoices]=useState<any[]>([]);const[items,setItems]=useState<any[]>([]);const[movements,setMovements]=useState<any[]>([]);const[selected,setSelected]=useState('Financial summary');
 const load=async()=>{const [a,b,i,it,m]=await Promise.all([fetch('/api/reports/summary'),fetch('/api/reports/cases'),fetch('/api/invoices'),fetch('/api/inventory'),fetch('/api/inventory/movements')]);if(a.ok)setS(await a.json());if(b.ok)setC(await b.json());if(i.ok)setInvoices(await i.json());if(it.ok)setItems(await it.json());if(m.ok)setMovements(await m.json())};useEffect(()=>{load()},[]);
 if(!s)return <section className="empty-module"><div><div className="empty-icon"><BarChart3/></div><h2>Reports</h2><p>Loading live reports from PostgreSQL...</p></div></section>;
 const cards:Array<{title:string;text:string;Icon:React.ComponentType<any>}>=[{title:'Financial summary',text:'Revenue, VAT, expenses and profit',Icon:Wallet},{title:'Invoices & payments',text:'Collections and outstanding balances',Icon:Receipt},{title:'Case profitability',text:'Revenue, direct costs and margin per case',Icon:FileText},{title:'Inventory',text:'Stock value and low-stock items',Icon:Boxes},{title:'Staff activity',text:'Warehouse withdrawals and audit trail',Icon:Users},{title:'VAT',text:'Output VAT, input VAT and net payable',Icon:BarChart3}];
 const render=()=>{if(selected==='Financial summary')return <><div className="stats-grid"><div className="stat-card"><span>Net revenue</span><strong>€{s.revenue.toFixed(2)}</strong></div><div className="stat-card"><span>Expenses</span><strong>€{s.expenses.toFixed(2)}</strong></div><div className="stat-card"><span>Profit</span><strong>€{s.grossProfit.toFixed(2)}</strong><small>{s.profitMargin.toFixed(1)}% margin</small></div><div className="stat-card"><span>Collections</span><strong>€{s.collections.toFixed(2)}</strong></div></div></>;
 if(selected==='Invoices & payments')return <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.id}</td><td>{i.patientName}</td><td>€{i.amount.toFixed(2)}</td><td>€{i.paid.toFixed(2)}</td><td>€{(i.amount-i.paid).toFixed(2)}</td><td>{i.status}</td></tr>)}</tbody></table></div>;
 if(selected==='Case profitability')return <div className="table-wrap"><table><thead><tr><th>Case</th><th>Patient</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{c.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.patient}</td><td>€{x.revenue.toFixed(2)}</td><td>€{x.cost.toFixed(2)}</td><td>€{x.profit.toFixed(2)}</td><td>{x.margin.toFixed(1)}%</td></tr>)}</tbody></table></div>;
 if(selected==='Inventory')return <div className="table-wrap"><table><thead><tr><th>Code</th><th>Item</th><th>Stock</th><th>Min</th><th>Value</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.id}</td><td>{i.name}</td><td>{i.stock}</td><td>{i.minStock}</td><td>€{(i.stock*i.unitCost).toFixed(2)}</td><td>{i.stock<=i.minStock?'Low stock':'OK'}</td></tr>)}</tbody></table></div>;
 if(selected==='Staff activity')return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Item</th><th>Movement</th><th>Patient</th><th>Case</th><th>Qty</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.date).toLocaleString()}</td><td>{m.employeeName}</td><td>{m.itemName}</td><td>{m.type}</td><td>{m.patientId||'—'}</td><td>{m.caseId||'—'}</td><td>{m.quantity}</td></tr>)}</tbody></table></div>;
 return <><div className="stats-grid"><div className="stat-card"><span>Output VAT</span><strong>€{s.outputVat.toFixed(2)}</strong></div><div className="stat-card"><span>Input VAT</span><strong>€{s.inputVat.toFixed(2)}</strong></div><div className="stat-card"><span>VAT payable</span><strong>€{s.vatPayable.toFixed(2)}</strong></div></div><p className="muted">Output VAT minus recoverable input VAT.</p></>};
 return <><div className="page-heading"><div><p className="eyebrow">MANAGEMENT REPORTING</p><h1>Reports</h1><p className="muted">Live operational and financial reporting.</p></div></div><div className="report-grid">{cards.map(({title,text,Icon})=><button className={`report-card ${selected===title?'active':''}`} key={title} onClick={()=>setSelected(title)}><div className="report-icon"><Icon size={24}/></div><strong>{title}</strong><span>{text}</span></button>)}</div><section className="panel" style={{marginTop:20}}><div className="panel-header"><div><h2>{selected}</h2><p>Live data from PostgreSQL.</p></div><button className="secondary" onClick={load}>Refresh</button></div>{render()}</section></>}
