import crypto from 'node:crypto';
import { PrismaClient } from '@prisma/client';

const prisma=new PrismaClient();
let ready;
const init=()=>ready??=(async()=>{await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "resq_auth_user" ("id" text PRIMARY KEY,"username" text UNIQUE NOT NULL,"name" text NOT NULL,"email" text,"password_hash" text NOT NULL,"password_salt" text NOT NULL,"roles" text[] NOT NULL DEFAULT ARRAY[]::text[],"permissions" jsonb NOT NULL DEFAULT '[]'::jsonb,"active" boolean NOT NULL DEFAULT true,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now())`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "resq_auth_session" ("token" text PRIMARY KEY,"user_id" text NOT NULL REFERENCES "resq_auth_user"("id") ON DELETE CASCADE,"expires_at" timestamptz NOT NULL)`);})());
const hash=(password,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(password,salt,64).toString('hex')});
const verify=(password,salt,expected)=>{try{return crypto.timingSafeEqual(Buffer.from(expected,'hex'),crypto.scryptSync(password,salt,64))}catch{return false}};
const cookie=(token,maxAge=604800)=>`resq_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`;
const id=()=>crypto.randomUUID();
const safe=u=>({id:u.id,username:u.username,name:u.name,email:u.email||'',roles:u.roles||[],permissions:Array.isArray(u.permissions)?u.permissions:[],active:Boolean(u.active)});
async function current(req){await init();const m=req.headers.cookie?.match(/(?:^|;\\s*)resq_session=([^;]+)/);if(!m)return null;const rows=await prisma.$queryRawUnsafe(`SELECT u.* FROM "resq_auth_session" s JOIN "resq_auth_user" u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>now() AND u.active=true`,m[1]);return rows[0]||null}
async function handler(req,res){await init();const path=String(req.url||'').split('?')[0].replace(/^\/api\/auth\/?/,'');try{
 if(req.method==='GET'&&path==='status'){const u=await current(req);return res.json({authenticated:Boolean(u),user:u?safe(u):null})}
 if(req.method==='POST'&&path==='setup'){const body=req.body||{};const count=await prisma.$queryRawUnsafe(`SELECT count(*)::int AS n FROM "resq_auth_user"`);if(Number(count[0].n)>0)return res.status(409).json({error:'An administrator account already exists'});if(!body.name||!body.username||!body.password||String(body.password).length<8)return res.status(400).json({error:'Name, username and password of at least 8 characters are required'});const {salt,hash:ph}=hash(String(body.password));const u=await prisma.$queryRawUnsafe(`INSERT INTO "resq_auth_user" (id,username,name,email,password_hash,password_salt,roles,permissions) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb) RETURNING *`,id(),String(body.username).trim(),String(body.name).trim(),body.email||null,ph,salt,['MANAGER'],'[]');const token=crypto.randomBytes(32).toString('hex');await prisma.$executeRawUnsafe(`INSERT INTO "resq_auth_session" (token,user_id,expires_at) VALUES ($1,$2,now()+interval '7 days')`,token,u[0].id);res.setHeader('Set-Cookie',cookie(token));return res.status(201).json({user:safe(u[0])})}
 if(req.method==='POST'&&path==='login'){const body=req.body||{};const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "resq_auth_user" WHERE username=$1 LIMIT 1`,String(body.username||'').trim());const u=rows[0];if(!u||!u.active||!verify(String(body.password||''),u.password_salt,u.password_hash))return res.status(401).json({error:'Invalid username or password'});const token=crypto.randomBytes(32).toString('hex');await prisma.$executeRawUnsafe(`INSERT INTO "resq_auth_session" (token,user_id,expires_at) VALUES ($1,$2,now()+interval '7 days')`,token,u.id);res.setHeader('Set-Cookie',cookie(token));return res.json({user:safe(u)})}
 if(req.method==='POST'&&path==='logout'){const m=req.headers.cookie?.match(/(?:^|;\\s*)resq_session=([^;]+)/);if(m)await prisma.$executeRawUnsafe(`DELETE FROM "resq_auth_session" WHERE token=$1`,m[1]);res.setHeader('Set-Cookie',cookie('',0));return res.json({ok:true})}
 if(req.method==='POST'&&path==='change-password'){const u=await current(req);if(!u)return res.status(401).json({error:'Not authenticated'});const body=req.body||{};if(!verify(String(body.currentPassword||''),u.password_salt,u.password_hash))return res.status(401).json({error:'Current password is incorrect'});if(String(body.newPassword||'').length<8)return res.status(400).json({error:'New password must be at least 8 characters'});const {salt,hash:ph}=hash(String(body.newPassword));await prisma.$executeRawUnsafe(`UPDATE "resq_auth_user" SET password_hash=$1,password_salt=$2,updated_at=now() WHERE id=$3`,ph,salt,u.id);return res.json({ok:true})}
 return res.status(404).json({error:'Authentication endpoint not found'});
}catch(e){console.error('auth',e);return res.status(500).json({error:'Authentication service error'})}}
export default handler;
