import crypto from 'node:crypto';
import { PrismaClient } from '@prisma/client';
const prisma=new PrismaClient();
let ready;
const init=()=>ready??=(async()=>{await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "resq_auth_user" ("id" text PRIMARY KEY,"username" text UNIQUE NOT NULL,"name" text NOT NULL,"email" text,"password_hash" text NOT NULL,"password_salt" text NOT NULL,"roles" text[] NOT NULL DEFAULT ARRAY[]::text[],"permissions" jsonb NOT NULL DEFAULT '[]'::jsonb,"active" boolean NOT NULL DEFAULT true,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now())`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "resq_auth_session" ("token" text PRIMARY KEY,"user_id" text NOT NULL REFERENCES "resq_auth_user"("id") ON DELETE CASCADE,"expires_at" timestamptz NOT NULL)`);})();
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>({s,h:crypto.scryptSync(p,s,64).toString('hex')});
const safe=u=>({id:u.id,username:u.username,name:u.name,email:u.email||'',roles:u.roles||[],permissions:Array.isArray(u.permissions)?u.permissions:[],active:Boolean(u.active)});
async function auth(req){await init();const m=req.headers.cookie?.match(/(?:^|;\\s*)resq_session=([^;]+)/);if(!m)return null;const r=await prisma.$queryRawUnsafe(`SELECT u.* FROM "resq_auth_session" s JOIN "resq_auth_user" u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>now() AND u.active=true`,m[1]);return r[0]||null}
async function handler(req,res){try{const u=await auth(req);if(!u)return res.status(401).json({error:'Not authenticated'});if(!u.roles?.includes('MANAGER'))return res.status(403).json({error:'Manager access required'});const base=String(req.url||'').split('?')[0].replace(/^\/api\/users/,'');
if(req.method==='GET'&&!base){const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "resq_auth_user" ORDER BY name`);return res.json(rows.map(safe))}
if(req.method==='POST'&&!base){const b=req.body||{};if(!b.name||!b.username||!b.password||String(b.password).length<8)return res.status(400).json({error:'Name, username and password of at least 8 characters are required'});const roles=Array.isArray(b.roles)?b.roles:[];if(!roles.length)return res.status(400).json({error:'Select at least one role'});const {s,h}=hash(String(b.password));try{const rows=await prisma.$queryRawUnsafe(`INSERT INTO "resq_auth_user" (id,username,name,email,password_hash,password_salt,roles,permissions,active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,true) RETURNING *`,crypto.randomUUID(),String(b.username).trim(),String(b.name).trim(),b.email||null,h,s,roles,JSON.stringify(b.permissions||[]));return res.status(201).json(safe(rows[0]))}catch(e){if(String(e.message).includes('unique'))return res.status(409).json({error:'Username already exists'});throw e}}
const uid=base.replace(/^\/+/, '').split('/')[0];if(!uid)return res.status(404).json({error:'User not found'});
if(req.method==='PATCH'){const rows=await prisma.$queryRawUnsafe(`SELECT * FROM "resq_auth_user" WHERE id=$1`,uid);const old=rows[0];if(!old)return res.status(404).json({error:'User not found'});const b=req.body||{};const roles=Array.isArray(b.roles)?b.roles:old.roles;if(!roles.length)return res.status(400).json({error:'Select at least one role'});let sql=`UPDATE "resq_auth_user" SET name=$1,email=$2,roles=$3,permissions=$4::jsonb,active=$5,updated_at=now()`;const vals=[b.name??old.name,b.email??old.email,roles,JSON.stringify(b.permissions||[]),b.active===undefined?old.active:Boolean(b.active)];if(b.password){const {s,h}=hash(String(b.password));sql+=`,password_hash=$6,password_salt=$7`;vals.push(h,s)}sql+=` WHERE id=$${vals.length+1} RETURNING *`;vals.push(uid);const out=await prisma.$queryRawUnsafe(sql,...vals);return res.json(safe(out[0]))}
return res.status(404).json({error:'User endpoint not found'});
}catch(e){console.error('users',e);return res.status(500).json({error:'Unable to process user request'})}}
export default handler;
